version: "3.9"

services:
  dbautenticacion:
    container_name: dbautenticacion
    build:
      context: ./Bases_de_datos/Autenticacion
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: autenticacion
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - crediya
    ports:
      - "3306:3306"
    volumes:
      - dbautenticacion_data:/var/lib/mysql

  dbsolicitudes:
    container_name: dbsolicitudes
    build:
      context: ./Bases_de_datos/Solicitudes
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: solicitudes
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - crediya
    ports:
      - "3307:3307"  
    volumes:
      - dbsolicitudes_data:/var/lib/mysql
    



  autenticacion:
    container_name: autenticacion
    build:
      context: ./Autenticacion
      dockerfile: deployment/Dockerfile
    environment:
      MYSQL_HOST: dbautenticacion   
      MYSQL_PORT: 3306
      MYSQL_DATABASE: autenticacion
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_SSL_ENABLED: "true"
      JWT_SECRET: my-super-secret-key-1234567890abcdef
      GATEWAY: http://api-gateway:8080
    depends_on:
      - dbautenticacion             
    ports:
      - "8082:8082"
    networks:
      - crediya

  solicitudes:
    container_name: solicitudes
    build:
      context: ./Solicitudes
      dockerfile: deployment/Dockerfile
    environment:
      MYSQL_HOST: dbsolicitudes
      MYSQL_PORT: 3307
      MYSQL_DATABASE: solicitudes
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_SSL_ENABLED: "true"
      USUARIO_API_URL: http://autenticacion:8082
    depends_on:
      - dbsolicitudes
      - autenticacion
    ports:
      - "8081:8081"
    networks:
      - crediya

  api-gateway:
    container_name: api-gateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    environment:
      SERVICES_AUTH_URI: http://autenticacion:8082
      SERVICES_AUTH_PUBLIC_PATHS: /api/v1/login
      SERVICES_AUTH_PRIVATE_PATHS: /api/v1/usuarios,/api/v1/validar
      SERVICES_SOLICITUDES_URI: http://solicitudes:8081
      SERVICES_SOLICITUDES_PATHS: /api/v1/solicitud
      JWT_SECRET: my-super-secret-key-1234567890abcdef
    ports:
      - "8080:8080"
    depends_on:
      - solicitudes
      - autenticacion
    networks:
      - crediya

volumes:
  dbautenticacion_data:
  dbsolicitudes_data:

networks:
  crediya:
    driver: bridge
